---
# tasks file for configure_docker
- name: configuring yum repository
  yum_repository: 
    name: docker_installation
    description: docker repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: no
    state: present 

- name: installing docker and python
  package:
    name: 
      - docker-ce-3:18.09.1-3.el7
      - python3
    state: present

- name: staring docker service
  service:
    name: docker
    state: started

- name: installing pip for docker
  command: pip3 install docker
   
