---
# tasks file for k8s-slave-node
- name: installing docker in slave node
  yum:
    name: docker
    state: present

- name: enabling and starting docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: copying kubernetes.repo file into /etc/yum.repos.d/ directory
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: installing kubeadm kubelet kubectl
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - iproute-tc
    state: present
    disable_excludes: kubernetes
                                                                                                                                                                                                                
- name: enabling and starting kubelet daemon
  service:
    name: kubelet
    state: started
    enabled: yes

- name: changing docker network driver from cgroup to systemd
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
                              
- name: enabling and starting kubelet daemon
  service:
    name: docker
    state: restarted

- name: modifying iproute-tc settings
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf 

- name: restarting sysctl
  command: "sysctl --system"
  
 
